/* eslint-disable react-refresh/only-export-components, no-irregular-whitespace */
import { createContext, useContext, useEffect, useMemo, useState, type MouseEvent, type ReactNode } from 'react'
import { Alert, Button, Form, Input, Spin, Typography, message } from 'antd'
import { ArrowRight, BarChart3, Bot, ChevronDown, Database, Github, Globe2, LockKeyhole, Mail, Moon, Rocket, ShieldCheck, Sparkles, Sun, UserRound, Users, Workflow } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { api, setCsrfToken } from './api'
import type { User } from './types'

interface AuthContextValue { user: User; logout: () => Promise<void>; updateUser: (user: User) => void }
const AuthContext = createContext<AuthContextValue | null>(null)
export function useAuth() { const value = useContext(AuthContext); if (!value) throw new Error('AuthContext is missing'); return value }

declare global { interface Window { turnstile?: { render: (el: HTMLElement, opts: Record<string, unknown>) => void } } }
function Captcha({ enabled, siteKey, onChange }: { enabled: boolean; siteKey?: string; onChange: (value?: string) => void }) {
  const [element, setElement] = useState<HTMLDivElement | null>(null)
  useEffect(() => {
    if (!enabled || !siteKey || !element) return
    let timer: number | undefined
    const render = () => { if (window.turnstile) window.turnstile.render(element, { sitekey: siteKey, callback: onChange, 'expired-callback': () => onChange(undefined), 'error-callback': () => onChange(undefined) }); else timer = window.setTimeout(render, 250) }
    render()
    return () => { if (timer) window.clearTimeout(timer) }
  }, [enabled, siteKey, element, onChange])
  return enabled ? <div ref={setElement} className="captcha-widget" /> : null
}

type HomeSite = { site_name: string; site_subtitle: string; logo_url: string }
export function LegacyHomePage({ site, user, onLogout }: { site: HomeSite; user?: User; onLogout?: () => void }) {
  const navigate = useNavigate()
  return <main className="home-page">
    <header className="home-header">
      <div className="home-brand">{site.logo_url ? <img className="auth-site-logo home-logo" src={`${site.logo_url}?home=1`} alt={site.site_name} /> : <span className="brand-mark small">VX</span>}<strong>{site.site_name}</strong></div>
      <nav className="home-actions" aria-label="账户入口">{user ? <><span className="home-user">已登录：{user.username}</span><Button type="primary" onClick={() => navigate('/dashboard')}>进入系统</Button><Button onClick={onLogout}>退出登录</Button></> : <><Button type="text" onClick={() => navigate('/login')}>登录</Button><Button type="primary" onClick={() => navigate('/register')}>注册</Button></>}</nav>
    </header>
    <section className="home-hero"><Typography.Title>{site.site_name}</Typography.Title><Typography.Paragraph>{site.site_subtitle || '数据驱动内容运营'}</Typography.Paragraph>{!user && <Button type="primary" size="large" onClick={() => navigate('/login')}>开始使用</Button>}</section>
  </main>
}

export function LegacyModernHomePage({ site, user, onLogout }: { site: HomeSite; user?: User; onLogout?: () => void }) {
  const navigate = useNavigate()
  const [language, setLanguage] = useState<'zh' | 'en'>(() => localStorage.getItem('vx_home_language') === 'en' ? 'en' : 'zh')
  const [homeMode, setHomeMode] = useState<'dark' | 'light'>(() => localStorage.getItem('vx_home_mode') === 'light' ? 'light' : 'dark')
  const english = language === 'en'
  const text = english ? {
    home: 'Home', features: 'Features', github: 'GitHub', docs: 'Documentation', login: 'Log in', register: 'Sign up', enter: 'Open workspace', logout: 'Log out', kicker: 'Open source · Data analytics · AI workspace', heroTitle: 'Make data-driven decisions with AI for every idea', heroDescription: 'An all-in-one data analytics and AI workspace for data sources, visualization, intelligent analysis and automation.', tryNow: 'Get started', source: 'View source', dataOverview: 'Data overview', analysis: 'Data analysis', aiAssistant: 'AI assistant', dataSource: 'Data sources', system: 'Settings', dataVolume: 'Total data', tasks: 'Analysis tasks', generated: 'AI generated', trend: 'Data trends', assistant: 'AI Assistant', footerAbout: 'About us', footerDocs: 'Documentation', footerProjects: 'Related projects', footerLinks: 'Friend links', aboutProject: 'About project', contact: 'Contact us', install: 'Installation', guide: 'User guide', apiDocs: 'API docs', openApi: 'One API', coai: 'CoAI', privacy: 'Privacy and security'
  } : {
    home: '首页', features: '功能特性', github: 'GitHub', docs: '项目文档', login: '登录', register: '注册', enter: '进入系统', logout: '退出', kicker: '开源 · 数据分析 · AI 工作台', heroTitle: '让数据驱动决策，让 AI 赋能每一个想法', heroDescription: '一站式数据分析与 AI 工作台，支持多数据源接入、数据可视化、智能分析与自动化任务，帮助你更高效地处理数据、发现价值。', tryNow: '立即体验', source: '查看源码', dataOverview: '数据总览', analysis: '数据分析', aiAssistant: 'AI 助手', dataSource: '数据源', system: '系统设置', dataVolume: '总数据量', tasks: '分析任务', generated: 'AI 生成', trend: '数据趋势', assistant: '智能助手', footerAbout: '关于我们', footerDocs: '文档', footerProjects: '相关项目', footerLinks: '友情链接', aboutProject: '关于项目', contact: '联系我们', install: '安装部署', guide: '使用指南', apiDocs: 'API 文档', openApi: 'One API', coai: 'CoAI', privacy: '安全可靠'
  }
  const setLanguagePersisted = (next: 'zh' | 'en') => { setLanguage(next); localStorage.setItem('vx_home_language', next) }
  const setHomeModePersisted = (next: 'dark' | 'light') => { setHomeMode(next); localStorage.setItem('vx_home_mode', next) }
  const githubUrl = 'https://github.com/huizhang556/vx_data_watch'
  const features = [
    { icon: <Database />, tone: 'cyan', title: english ? 'Multi-source access' : '多数据源接入', description: english ? 'Connect databases, files and APIs with ease.' : '支持多种数据源（数据库、文件、API 等），轻松接入你的数据。', tags: ['MySQL', 'PostgreSQL', 'API', '...'] },
    { icon: <BarChart3 />, tone: 'teal', title: english ? 'Analytics & visualization' : '数据分析与可视化', description: english ? 'Turn complex data into clear, useful insights.' : '强大的数据处理与分析能力，丰富的可视化图表，直观呈现数据价值。', tags: english ? ['Charts', 'Reports', 'Dashboards', '...'] : ['图表', '报表', '仪表盘', '...'] },
    { icon: <Bot />, tone: 'purple', title: english ? 'AI assistant' : 'AI 智能助手', description: english ? 'Ask, analyze and generate with multiple AI models.' : '集成多种大模型，支持智能问答、数据分析、内容生成等 AI 能力。', tags: ['GPT', 'Claude', 'Gemini', '...'] },
    { icon: <Workflow />, tone: 'gold', title: english ? 'Automation' : '自动化任务', description: english ? 'Schedule tasks, sync data and automate workflows.' : '定时任务、数据同步、智能分析、一键配置，自动运行，更释放你的时间。', tags: english ? ['Schedules', 'Sync', 'Automation', '...'] : ['定时任务', '数据同步', '自动化', '...'] },
  ]
  return <main className={`home-page home-page-modern ${homeMode === 'light' ? 'home-light-mode' : 'home-dark-mode'}`}>
    <header className="home-modern-header">
      <a className="home-modern-brand" href="#top" aria-label={site.site_name}><span className="home-modern-mark">VX</span><span>{site.site_name || 'VX Data Watch'}</span></a>
      <nav className="home-modern-nav" aria-label={text.home}><a className="active" href="#top">{text.home}</a><a href="#features">{text.features}</a><a href={githubUrl} target="_blank" rel="noreferrer">{text.github}</a><a href={githubUrl} target="_blank" rel="noreferrer">{text.docs}</a></nav>
      <div className="home-modern-actions"><button className="home-icon-button" type="button" onClick={() => setHomeModePersisted(homeMode === 'dark' ? 'light' : 'dark')} title={homeMode === 'dark' ? '切换白天模式' : '切换黑夜模式'} aria-label="切换显示模式">{homeMode === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button className="home-language" type="button" onClick={() => setLanguagePersisted(english ? 'zh' : 'en')} title="切换语言"><Globe2 size={16} />{english ? 'English' : '中文'}<ChevronDown size={14} /></button>{user ? <><span className="home-modern-user">{user.username}</span><button className="home-outline-button" type="button" onClick={() => navigate('/dashboard')}>{text.enter}</button><button className="home-primary-button" type="button" onClick={onLogout}>{text.logout}</button></> : <><button className="home-outline-button" type="button" onClick={() => navigate('/login')}>{text.login}</button><button className="home-primary-button" type="button" onClick={() => navigate('/register')}>{text.register}</button></>}</div>
    </header>
    <section className="home-modern-hero" id="top"><div className="home-modern-copy"><div className="home-kicker"><Github size={16} />开源 · 数据分析 · AI 工作台</div><h1>{site.site_name || 'VX Data Watch'}</h1><h2>{site.site_subtitle || '让数据驱动决策，让 AI 赋能每一个想法'}</h2><p>一站式数据分析与 AI 工作台，支持多数据源接入、数据可视化、智能分析与自动化任务，帮助你更高效地处理数据、发现价值。</p><div className="home-hero-actions"><button className="home-primary-button home-large-button" type="button" onClick={() => navigate(user ? '/dashboard' : '/login')}><Rocket size={18} />立即体验<ArrowRight size={18} /></button><a className="home-outline-button home-large-button" href={githubUrl} target="_blank" rel="noreferrer"><Github size={18} />查看源码</a></div></div><div className="home-dashboard-art" aria-label="数据分析工作台预览"><div className="home-orbit home-orbit-one" /><div className="home-orbit home-orbit-two" /><div className="home-globe" /><div className="home-panel-window"><div className="home-window-dots"><i /><i /><i /></div><div className="home-panel-sidebar"><b>⌂　数据总览</b><span>▥　数据分析</span><span>◉　AI 助手</span><span>▤　数据源</span><span>⚙　系统设置</span></div><div className="home-panel-main"><div className="home-stat-row"><div><small>总数据量</small><strong>1,248,690</strong><em>↑ 12.6%</em></div><div><small>分析任务</small><strong>286</strong><em>↑ 18.3%</em></div><div><small>AI 生成</small><strong>142</strong><em>↑ 32.7%</em></div></div><div className="home-chart"><small>数据趋势</small><div className="home-chart-lines"><b /><b /><b /><b /><b /><b /></div><div className="home-bars"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div></div><div className="home-ai-card"><Sparkles size={22} /><strong>AI</strong><span>智能助手</span></div></div></section>
    <section className="home-feature-grid" id="features">{features.map((feature) => <article className="home-feature-card" key={feature.title}><div className={`home-feature-icon ${feature.tone}`}>{feature.icon}</div><h3>{feature.title}</h3><p>{feature.description}</p><div className="home-feature-tags">{feature.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</section>
    <section className="home-open-section"><h2>开源 · 共享 · 共建更好的数据世界</h2><div className="home-open-grid"><span><Github /><b>开源项目</b><small>完全开源，社区驱动</small></span><span><Sparkles /><b>持续更新</b><small>不断优化，功能迭代</small></span><span><Users /><b>社区支持</b><small>欢迎你的加入</small></span><span><ShieldCheck /><b>安全可靠</b><small>数据本地化，隐私可控</small></span></div></section>
  </main>
}

export function LegacyBrokenHomePage({ site, user, onLogout }: { site: HomeSite; user?: User; onLogout?: () => void }) {
  const navigate = useNavigate()
  const [language, setLanguage] = useState<'zh' | 'en'>(() => localStorage.getItem('vx_home_language') === 'en' ? 'en' : 'zh')
  const [mode, setMode] = useState<'dark' | 'light'>(() => localStorage.getItem('vx_home_mode') === 'light' ? 'light' : 'dark')
  const en = language === 'en'
  const copy = en ? {
    home: 'Home', features: 'Features', docs: 'Documentation', kicker: 'Open source · Data analytics · AI workspace', hero: 'Make data-driven decisions with AI for every idea', desc: 'An all-in-one data analytics and AI workspace for data sources, visualization, intelligent analysis and automation.', start: 'Get started', source: 'View source', login: 'Log in', register: 'Sign up', enter: 'Open workspace', logout: 'Log out', overview: 'Data overview', analysis: 'Data analysis', assistant: 'AI assistant', sources: 'Data sources', settings: 'Settings', total: 'Total data', tasks: 'Analysis tasks', generated: 'AI generated', trend: 'Data trends', ai: 'AI Assistant', about: 'About us', docsCol: 'Documentation', projects: 'Related projects', links: 'Friend links', aboutProject: 'About project', contact: 'Contact us', install: 'Installation', guide: 'User guide', api: 'API docs', oneApi: 'One API', coai: 'CoAI', security: 'Privacy and security', cards: [['Multi-source access', 'Connect databases, files and APIs with ease.', ['MySQL', 'PostgreSQL', 'API', '...']], ['Analytics & visualization', 'Turn complex data into clear, useful insights.', ['Charts', 'Reports', 'Dashboards', '...']], ['AI assistant', 'Ask, analyze and generate with multiple AI models.', ['GPT', 'Claude', 'Gemini', '...']], ['Automation', 'Schedule tasks, sync data and automate workflows.', ['Schedules', 'Sync', 'Automation', '...']]],
  } : {
    home: '首页', features: '功能特性', docs: '项目文档', kicker: '开源 · 数据分析 · AI 工作台', hero: '让数据驱动决策，让 AI 赋能每一个想法', desc: '一站式数据分析与 AI 工作台，支持多数据源接入、数据可视化、智能分析与自动化任务，帮助你更高效地处理数据、发现价值。', start: '立即体验', source: '查看源码', login: '登录', register: '注册', enter: '进入系统', logout: '退出', overview: '数据总览', analysis: '数据分析', assistant: 'AI 助手', sources: '数据源', settings: '系统设置', total: '总数据量', tasks: '分析任务', generated: 'AI 生成', trend: '数据趋势', ai: '智能助手', about: '关于我们', docsCol: '文档', projects: '相关项目', links: '友情链接', aboutProject: '关于项目', contact: '联系我们', install: '安装部署', guide: '使用指南', api: 'API 文档', oneApi: 'One API', coai: 'CoAI', security: '安全可靠', cards: [['多数据源接入', '支持多种数据源（数据库、文件、API 等），轻松接入你的数据。', ['MySQL', 'PostgreSQL', 'API', '...']], ['数据分析与可视化', '强大的数据处理与分析能力，丰富的可视化图表，直观呈现数据价值。', ['图表', '报表', '仪表盘', '...']], ['AI 智能助手', '集成多种大模型，支持智能问答、数据分析、内容生成等 AI 能力。', ['GPT', 'Claude', 'Gemini', '...']], ['自动化任务', '定时任务、数据同步、智能分析、一键配置，自动运行，更释放你的时间。', ['定时任务', '数据同步', '自动化', '...']]],
  }
  const githubUrl = 'https://github.com/huizhang556/vx_data_watch'
  const cards = copy.cards.map((card, index) => ({ icon: [<Database />, <BarChart3 />, <Bot />, <Workflow />][index], tone: ['cyan', 'teal', 'purple', 'gold'][index], title: String(card[0]), description: String(card[1]), tags: (Array.isArray(card[2]) ? card[2] : []) as string[] }))
  const toggleMode = () => { const next = mode === 'dark' ? 'light' : 'dark'; setMode(next); localStorage.setItem('vx_home_mode', next) }
  const toggleLanguage = () => { const next = en ? 'zh' : 'en'; setLanguage(next); localStorage.setItem('vx_home_language', next) }
  const emptyLink = (event: MouseEvent<HTMLAnchorElement>) => event.preventDefault()
  return <main className={`home-page home-page-modern ${mode === 'light' ? 'home-light-mode' : 'home-dark-mode'}`}>
    <header className="home-modern-header"><a className="home-modern-brand" href="#top" aria-label={site.site_name}><span className="home-modern-mark">VX</span><span>{site.site_name || 'HG-工具小屋'}</span></a><nav className="home-modern-nav" aria-label={copy.home}><a className="active" href="#top">{copy.home}</a><a href="#features">{copy.features}</a><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a href={githubUrl} target="_blank" rel="noreferrer">{copy.docs}</a></nav><div className="home-modern-actions"><button className="home-icon-button" type="button" onClick={toggleMode} title={mode === 'dark' ? '切换白天模式' : '切换黑夜模式'} aria-label="切换显示模式">{mode === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button className="home-language" type="button" onClick={toggleLanguage} title="切换语言"><Globe2 size={16} />{en ? 'English' : '中文'}<ChevronDown size={14} /></button>{user ? <><span className="home-modern-user">{user.username}</span><button className="home-outline-button" type="button" onClick={() => navigate('/dashboard')}>{copy.enter}</button><button className="home-primary-button" type="button" onClick={onLogout}>{copy.logout}</button></> : <><button className="home-outline-button" type="button" onClick={() => navigate('/login')}>{copy.login}</button><button className="home-primary-button" type="button" onClick={() => navigate('/register')}>{copy.register}</button></>}</div></header>
    <section className="home-modern-hero" id="top"><div className="home-modern-copy"><div className="home-kicker"><Github size={16} />{copy.kicker}</div><h1>{site.site_name || 'HG-工具小屋'}</h1><h2>{site.site_subtitle || copy.hero}</h2><p>{copy.desc}</p><div className="home-hero-actions"><button className="home-primary-button home-large-button" type="button" onClick={() => navigate(user ? '/dashboard' : '/login')}><Rocket size={18} />{copy.start}<ArrowRight size={18} /></button><a className="home-outline-button home-large-button" href={githubUrl} target="_blank" rel="noreferrer"><Github size={18} />{copy.source}</a></div></div><div className="home-dashboard-art" aria-label={copy.analysis}><div className="home-orbit home-orbit-one" /><div className="home-orbit home-orbit-two" /><div className="home-globe" /><div className="home-panel-window"><div className="home-window-dots"><i /><i /><i /></div><div className="home-panel-sidebar"><b>⌂　{copy.overview}</b><span>▥　{copy.analysis}</span><span>◉　{copy.assistant}</span><span>▤　{copy.sources}</span><span>⚙　{copy.settings}</span></div><div className="home-panel-main"><div className="home-stat-row"><div><small>{copy.total}</small><strong>1,248,690</strong><em>↑ 12.6%</em></div><div><small>{copy.tasks}</small><strong>286</strong><em>↑ 18.3%</em></div><div><small>{copy.generated}</small><strong>142</strong><em>↑ 32.7%</em></div></div><div className="home-chart"><small>{copy.trend}</small><div className="home-chart-lines"><b /><b /><b /><b /><b /><b /></div><div className="home-bars"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div></div><div className="home-ai-card"><Sparkles size={22} /><strong>AI</strong><span>{copy.ai}</span></div></div></section>
    <section className="home-feature-grid" id="features">{cards.map((card) => <article className="home-feature-card" key={card.title}><div className={`home-feature-icon ${card.tone}`}>{card.icon}</div><h3>{card.title}</h3><p>{card.description}</p><div className="home-feature-tags">{card.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</section>
    <section className="home-open-section"><h2>{en ? 'Open source · Share · Build a better data world' : '开源 · 共享 · 共建更好的数据世界'}</h2><div className="home-open-grid"><span><Github /><b>{en ? 'Open source' : '开源项目'}</b><small>{en ? 'Community driven' : '完全开源，社区驱动'}</small></span><span><Sparkles /><b>{en ? 'Always improving' : '持续更新'}</b><small>{en ? 'Iterate continuously' : '不断优化，功能迭代'}</small></span><span><Users /><b>{en ? 'Community' : '社区支持'}</b><small>{en ? 'You are welcome' : '欢迎你的加入'}</small></span><span><ShieldCheck /><b>{en ? 'Reliable' : '安全可靠'}</b><small>{copy.security}</small></span></div></section>
    <footer className="home-footer"><div><h3>{copy.about}</h3><a href="#" onClick={emptyLink}>{copy.aboutProject}</a><a href="#" onClick={emptyLink}>{copy.contact}</a><a href="#features" onClick={emptyLink}>{copy.features}</a></div><div><h3>{copy.docsCol}</h3><a href="#" onClick={emptyLink}>{copy.install}</a><a href="#" onClick={emptyLink}>{copy.guide}</a><a href="#" onClick={emptyLink}>{copy.api}</a></div><div><h3>{copy.projects}</h3><a href="#" onClick={emptyLink}>{copy.oneApi}</a><a href="#" onClick={emptyLink}>Midjourney-Proxy</a><a href="#" onClick={emptyLink}>new-api-key-tool</a></div><div><h3>{copy.links}</h3><a href="#" onClick={emptyLink}>{copy.coai}</a><a href="#" onClick={emptyLink}>new-api-horizon</a><a href="#" onClick={emptyLink}>GPT-Load</a><a href="#" onClick={emptyLink}>LangBot</a></div></footer>
  </main>
}

function HomePage({ site, user, onLogout }: { site: HomeSite; user?: User; onLogout?: () => void }) {
  const navigate = useNavigate()
  const [language, setLanguage] = useState<'zh' | 'en'>(() => localStorage.getItem('vx_home_language') === 'en' ? 'en' : 'zh')
  const [mode, setMode] = useState<'dark' | 'light'>(() => localStorage.getItem('vx_home_mode') === 'light' ? 'light' : 'dark')
  const en = language === 'en'
  const text = en ? {
    home: 'Home', features: 'Features', docs: 'Documentation', login: 'Log in', register: 'Sign up', enter: 'Open workspace', logout: 'Log out', kicker: 'Open source · Data analytics · AI workspace', hero: 'Make data-driven decisions with AI for every idea', description: 'An all-in-one data analytics and AI workspace for data sources, visualization, intelligent analysis and automation.', start: 'Get started', source: 'View source', overview: 'Data overview', analysis: 'Data analysis', assistant: 'AI assistant', sources: 'Data sources', settings: 'Settings', total: 'Total data', tasks: 'Analysis tasks', generated: 'AI generated', trend: 'Data trends', about: 'About us', documentation: 'Documentation', projects: 'Related projects', links: 'Friend links', security: 'Privacy and security'
  } : {
    home: '首页', features: '功能特性', docs: '项目文档', login: '登录', register: '注册', enter: '进入系统', logout: '退出', kicker: '开源 · 数据分析 · AI 工作台', hero: '让数据驱动决策，让 AI 赋能每一个想法', description: '一站式数据分析与 AI 工作台，支持多数据源接入、数据可视化、智能分析与自动化任务，帮助你更高效地处理数据、发现价值。', start: '立即体验', source: '查看源码', overview: '数据总览', analysis: '数据分析', assistant: 'AI 助手', sources: '数据源', settings: '系统设置', total: '总数据量', tasks: '分析任务', generated: 'AI 生成', trend: '数据趋势', about: '关于我们', documentation: '文档', projects: '相关项目', links: '友情链接', security: '安全可靠'
  }
  const githubUrl = 'https://github.com/huizhang556/vx_data_watch'
  const toggleLanguage = () => { const next = en ? 'zh' : 'en'; setLanguage(next); localStorage.setItem('vx_home_language', next) }
  const toggleMode = () => { const next = mode === 'dark' ? 'light' : 'dark'; setMode(next); localStorage.setItem('vx_home_mode', next) }
  const features = en ? [['Multi-source access', 'Connect databases, files and APIs with ease.'], ['Analytics and visualization', 'Turn complex data into clear, useful insights.'], ['AI assistant', 'Ask, analyze and generate with multiple AI models.'], ['Automation', 'Schedule tasks, sync data and automate workflows.']] : [['多数据源接入', '支持数据库、文件和 API 等多种数据源。'], ['数据分析与可视化', '用清晰的图表和报告呈现数据价值。'], ['AI 智能助手', '集成多种模型，支持问答、分析和内容生成。'], ['自动化任务', '定时任务、数据同步和智能分析自动运行。']]
  return <main className={`home-page home-page-modern ${mode === 'light' ? 'home-light-mode' : 'home-dark-mode'}`}>
    <header className="home-modern-header"><a className="home-modern-brand" href="#top" aria-label={site.site_name}><span className="home-modern-mark">VX</span><span>{site.site_name || 'HG-工具小屋'}</span></a><nav className="home-modern-nav" aria-label={text.home}><a className="active" href="#top">{text.home}</a><a href="#features">{text.features}</a><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a href={githubUrl} target="_blank" rel="noreferrer">{text.docs}</a></nav><div className="home-modern-actions"><button className="home-icon-button" type="button" onClick={toggleMode} title={mode === 'dark' ? '切换白天模式' : '切换黑夜模式'} aria-label="切换显示模式">{mode === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button className="home-language" type="button" onClick={toggleLanguage} title="切换语言"><Globe2 size={16} />{en ? 'English' : '中文'}<ChevronDown size={14} /></button>{user ? <><span className="home-modern-user">{user.username}</span><button className="home-outline-button" type="button" onClick={() => navigate('/dashboard')}>{text.enter}</button><button className="home-primary-button" type="button" onClick={onLogout}>{text.logout}</button></> : <><button className="home-outline-button" type="button" onClick={() => navigate('/login')}>{text.login}</button><button className="home-primary-button" type="button" onClick={() => navigate('/register')}>{text.register}</button></>}</div></header>
    <section className="home-modern-hero" id="top"><div className="home-modern-copy"><div className="home-kicker"><Github size={16} />{text.kicker}</div><h1>{site.site_name || 'HG-工具小屋'}</h1><h2>{site.site_subtitle || text.hero}</h2><p>{text.description}</p><div className="home-hero-actions"><button className="home-primary-button home-large-button" type="button" onClick={() => navigate(user ? '/dashboard' : '/login')}><Rocket size={18} />{text.start}<ArrowRight size={18} /></button><a className="home-outline-button home-large-button" href={githubUrl} target="_blank" rel="noreferrer"><Github size={18} />{text.source}</a></div></div><div className="home-dashboard-art" aria-label={text.analysis}><div className="home-orbit home-orbit-one" /><div className="home-orbit home-orbit-two" /><div className="home-globe" /><div className="home-panel-window"><div className="home-window-dots"><i /><i /><i /></div><div className="home-panel-sidebar"><b>⌂　{text.overview}</b><span>▥　{text.analysis}</span><span>◉　{text.assistant}</span><span>▤　{text.sources}</span><span>⚙　{text.settings}</span></div><div className="home-panel-main"><div className="home-stat-row"><div><small>{text.total}</small><strong>1,248,690</strong><em>↑ 12.6%</em></div><div><small>{text.tasks}</small><strong>286</strong><em>↑ 18.3%</em></div><div><small>{text.generated}</small><strong>142</strong><em>↑ 32.7%</em></div></div><div className="home-chart"><small>{text.trend}</small><div className="home-chart-lines"><b /><b /><b /><b /><b /><b /></div><div className="home-bars"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div></div><div className="home-ai-card"><Sparkles size={22} /><strong>AI</strong><span>{text.assistant}</span></div></div></section>
    <section className="home-feature-grid" id="features">{features.map(([title, description], index) => <article className="home-feature-card" key={title}><div className={`home-feature-icon ${['cyan', 'teal', 'purple', 'gold'][index]}`}>{[<Database />, <BarChart3 />, <Bot />, <Workflow />][index]}</div><h3>{title}</h3><p>{description}</p><div className="home-feature-tags"><span>{index === 0 ? 'API' : index === 1 ? 'Reports' : index === 2 ? 'Models' : 'Automation'}</span><span>...</span></div></article>)}</section>
    <section className="home-open-section"><h2>{en ? 'Open source · Share · Build a better data world' : '开源 · 分享 · 共建更好的数据世界'}</h2><div className="home-open-grid"><span><Github /><b>{en ? 'Open source' : '开源项目'}</b><small>{en ? 'Community driven' : '完全开源，社区驱动'}</small></span><span><Sparkles /><b>{en ? 'Always improving' : '持续更新'}</b><small>{en ? 'Iterate continuously' : '持续优化产品体验'}</small></span><span><Users /><b>{en ? 'Community' : '社区支持'}</b><small>{en ? 'You are welcome' : '欢迎你的加入'}</small></span><span><ShieldCheck /><b>{en ? 'Reliable' : '安全可靠'}</b><small>{text.security}</small></span></div></section>
    <footer className="home-footer"><div><h3>{text.about}</h3><a href="#" onClick={(event) => event.preventDefault()}>{en ? 'About project' : '关于项目'}</a><a href="#" onClick={(event) => event.preventDefault()}>{en ? 'Contact us' : '联系我们'}</a></div><div><h3>{text.documentation}</h3><a href="#" onClick={(event) => event.preventDefault()}>{en ? 'Installation' : '安装部署'}</a><a href="#" onClick={(event) => event.preventDefault()}>{en ? 'User guide' : '使用指南'}</a><a href="#" onClick={(event) => event.preventDefault()}>{en ? 'API docs' : 'API 文档'}</a></div><div><h3>{text.projects}</h3><a href="#" onClick={(event) => event.preventDefault()}>One API</a><a href="#" onClick={(event) => event.preventDefault()}>Midjourney-Proxy</a></div><div><h3>{text.links}</h3><a href="#" onClick={(event) => event.preventDefault()}>CoAI</a><a href="#" onClick={(event) => event.preventDefault()}>GPT-Load</a></div></footer>
  </main>
}

type Mode = 'login' | 'register' | 'reset'
const modeForPath = (pathname: string): Mode => pathname === '/register' ? 'register' : pathname === '/reset-password' ? 'reset' : 'login'
const usernameRule = { pattern: /^[A-Za-z0-9_.-]+$/, message: '用户名只能包含英文、数字、下划线、点和短横线' }
const passwordRule = { pattern: /^(?=.*[A-Za-z])(?=.*\d).+$/, message: '密码至少 10 位，并同时包含字母和数字' }
export function AuthGate({ children }: { children: ReactNode }) {
  const location = useLocation()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(true); const [initialized, setInitialized] = useState(false); const [user, setUser] = useState<User | null>(null); const [error, setError] = useState('')
  const [config, setConfig] = useState({ registration_enabled: false, captcha_enabled: false, captcha_site_key: '', site_name: 'HG-工具小屋', site_subtitle: '数据驱动内容运营', logo_url: '' }); const [mode, setMode] = useState<Mode>('login'); const [captcha, setCaptcha] = useState<string>(); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false)
  const [form] = Form.useForm()
  const captchaReady = !config.captcha_enabled || Boolean(captcha)
  useEffect(() => { setMode(modeForPath(location.pathname)) }, [location.pathname])
  useEffect(() => { if (user && ['/login', '/register', '/reset-password'].includes(location.pathname)) navigate('/dashboard', { replace: true }) }, [user, location.pathname, navigate])
  useEffect(() => { if (!user && !['/', '/login', '/register', '/reset-password'].includes(location.pathname)) navigate('/', { replace: true }) }, [user, location.pathname, navigate])
  useEffect(() => {
    const button = document.querySelector<HTMLButtonElement>('.auth-panel form button[type="submit"]')
    if (!button) return
    button.disabled = !captchaReady || busy
    button.setAttribute('aria-disabled', String(!captchaReady || busy))
  }, [captchaReady, busy, mode])
  useEffect(() => { void (async () => { try { const [status, authConfig] = await Promise.all([api<{ initialized: boolean }>('/api/setup/status'), api<typeof config>('/api/auth/config')]); setInitialized(status.initialized); setConfig(authConfig); if (status.initialized) { try { const me = await api<User>('/api/auth/me'); setCsrfToken(me.csrf_token); setUser(me) } catch { setUser(null) } } } catch (cause) { setError(cause instanceof Error ? cause.message : '无法连接后端') } finally { setLoading(false) } })() }, [])
  useEffect(() => {
    if (user !== null || !initialized) return
    void api<typeof config>('/api/auth/config').then(setConfig).catch(() => undefined)
  }, [user, initialized])
  useEffect(() => { const onUnauthorized = () => { setCsrfToken(); setUser(null); localStorage.removeItem('vx_account_id') }; window.addEventListener('vx:unauthorized', onUnauthorized); return () => window.removeEventListener('vx:unauthorized', onUnauthorized) }, [])
  const switchMode = (next: Mode) => { setMode(next); setError(''); setCaptcha(undefined); form.resetFields(); setEmail(''); navigate(next === 'register' ? '/register' : next === 'reset' ? '/reset-password' : '/login') }
  const finishLogin = (next: User) => { setCsrfToken(next.csrf_token); setUser(next); setInitialized(true); message.success('登录成功') }
  const submit = async (values: { username?: string; password: string; email?: string; code?: string }) => { setBusy(true); setError(''); try { if (mode === 'login') finishLogin(await api<User>(initialized ? '/api/auth/login' : '/api/setup', { method: 'POST', body: JSON.stringify({ ...values, captcha_token: captcha }) })); else if (mode === 'register') finishLogin(await api<User>('/api/auth/register', { method: 'POST', body: JSON.stringify({ ...values, captcha_token: captcha }) })); else finishLogin(await api<User>('/api/auth/password-reset', { method: 'POST', body: JSON.stringify({ email: values.email, code: values.code, new_password: values.password, captcha_token: captcha }) })) } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败') } finally { setBusy(false) } }
  const syncField = (name: string, value: string) => { form.setFieldValue(name, value); if (name === 'email') setEmail(value) }
  const sendCode = async (value?: string) => { const targetEmail = value || form.getFieldValue('email') || email; setBusy(true); try { await api(mode === 'register' ? '/api/auth/register/request-code' : '/api/auth/password-reset/request-code', { method: 'POST', body: JSON.stringify({ email: targetEmail, captcha_token: captcha }) }); message.success('验证码已发送，请检查邮箱') } catch (cause) { message.error(cause instanceof Error ? cause.message : '发送失败') } finally { setBusy(false) } }
  const logout = async () => { try { await api('/api/auth/logout', { method: 'POST' }) } catch { /* clear local state even if server is unavailable */ } finally { setCsrfToken(); setUser(null); setMode('login'); setCaptcha(undefined); form.resetFields(); localStorage.removeItem('vx_account_id'); window.history.replaceState({}, '', '/') } }
  const updateUser = (next: User) => { setUser(next); if (next.csrf_token) setCsrfToken(next.csrf_token) }
  const value = useMemo(() => user ? { user, logout, updateUser } : null, [user])
  if (loading) return <div className="center-screen"><Spin size="large" /></div>
  if (user) return <AuthContext.Provider value={value!}>{location.pathname === '/' ? <HomePage user={user} onLogout={() => void logout()} site={config} /> : children}</AuthContext.Provider>
  if (location.pathname === '/') return <HomePage site={config} />
  const isSetup = !initialized
  return <main className="auth-page"><section className="auth-panel">{config.logo_url ? <img className="auth-site-logo" src={`${config.logo_url}?auth=1`} alt={config.site_name} /> : <div className="brand-mark">VX</div>}<Typography.Title level={2}>{config.site_name}</Typography.Title><Typography.Paragraph type="secondary">{config.site_subtitle || (isSetup ? '创建首个本地管理员账号' : '使用账号进入数据工作台')}</Typography.Paragraph>{error && <Alert type="error" showIcon message={error} />}
    <Form form={form} layout="vertical" onFinish={submit} requiredMark={false} key={mode}>{(mode === 'login' || mode === 'register') && <Form.Item name="username" label="用户名" rules={[{ required: true, message: '请输入用户名' }, { min: 3, message: '用户名至少需要 3 个字符' }, usernameRule]}><Input prefix={<UserRound size={17} />} autoComplete="username" onChange={(event) => syncField('username', event.currentTarget.value)} onInput={(event) => syncField('username', event.currentTarget.value)} onBlur={(event) => syncField('username', event.currentTarget.value)} /></Form.Item>}{(mode === 'register' || mode === 'reset') && <Form.Item name="email" label="注册邮箱" rules={[{ required: true, type: 'email', message: '请输入有效邮箱' }]}><Input prefix={<Mail size={17} />} autoComplete="email" onChange={(event) => syncField('email', event.target.value)} onBlur={(event) => syncField('email', event.target.value)} /></Form.Item>}{mode !== 'login' && <Form.Item name="code" label="邮箱验证码" rules={[{ required: true, message: '请输入 6 位数字验证码' }, { len: 6, pattern: /^\d{6}$/, message: '验证码必须是 6 位数字' }]}><Input.Search enterButton="发送验证码" onSearch={() => { void sendCode(form.getFieldValue('email')) }} /></Form.Item>}<Form.Item name="password" label={mode === 'login' ? '密码' : '新密码'} rules={[{ required: true, message: '请输入密码' }, ...(mode === 'login' ? [] : [{ min: 10, message: '密码至少需要 10 个字符' }, passwordRule])]}><Input.Password prefix={<LockKeyhole size={17} />} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} onChange={(event) => syncField('password', event.currentTarget.value)} onInput={(event) => syncField('password', event.currentTarget.value)} onBlur={(event) => syncField('password', event.currentTarget.value)} /></Form.Item><Captcha enabled={config.captcha_enabled} siteKey={config.captcha_site_key} onChange={setCaptcha} /><Button block type="primary" htmlType="submit" size="large" loading={busy}>{isSetup ? '初始化系统' : mode === 'login' ? '登录' : mode === 'register' ? '注册并登录' : '重置密码并登录'}</Button></Form>
    {!isSetup && <div className="auth-links"><button type="button" onClick={() => switchMode('reset')}>重置密码</button>{config.registration_enabled && <button type="button" onClick={() => switchMode('register')}>注册账号</button>}{mode !== 'login' && <button type="button" onClick={() => switchMode('login')}>返回登录</button>}</div>}
  </section></main>
}
