import { expect, test } from '@playwright/test'
import path from 'node:path'

test('initializes, imports seven-day CSV, and renders desktop/mobile', async ({ page }) => {
  await page.route('**/api/system/versions', (route) => route.fulfill({ json: { current_version: '0.3.1', latest_version: '0.3.2', versions: [{ version: '0.3.2', published_at: '2026-08-19T00:00:00Z' }], repository: 'litehub/vx-data-watch', update_supported: true, deployment: 'docker' } }))
  await page.route('**/api/system/update-status', (route) => route.fulfill({ json: { state: 'idle', current_version: '0.3.1' } }))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '视频号数据分析' })).toBeVisible()
  await page.getByLabel('用户名').fill('admin')
  await page.getByLabel('密码').fill('secure-pass-123')
  await page.getByRole('button', { name: '初始化系统' }).click()
  await expect(page.getByText('数据概览', { exact: true }).first()).toBeVisible()

  await page.getByText('系统设置', { exact: true }).first().click()
  await expect(page.getByText('v0.3.1')).toBeVisible()
  await expect(page.getByRole('button', { name: '更新并重启' })).toBeVisible()
  await page.getByRole('button', { name: '新增账号' }).click()
  await page.getByLabel('账号名称').fill('样例视频号')
  await page.getByLabel('备注').fill('端到端测试')
  await page.getByRole('dialog').locator('button[type="submit"]').click()
  await expect(page.getByText('样例视频号').last()).toBeVisible()

  await page.getByText('数据导入', { exact: true }).first().click()
  await page.getByRole('textbox', { name: '数据截止日期' }).fill('2026-08-16')
  await page.getByRole('textbox', { name: '数据截止日期' }).press('Enter')
  const csvPath = path.resolve(import.meta.dirname, 'fixtures/account.csv')
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles(csvPath)
  await page.getByRole('button', { name: '解析预览' }).click()
  await expect(page.getByText('新增 7')).toBeVisible()
  await page.getByRole('button', { name: '确认导入' }).click()
  await expect(page.getByText(/导入完成/)).toBeVisible()

  await page.getByText('数据概览', { exact: true }).first().click()
  await page.getByRole('textbox', { name: '请选择日期' }).fill('2026-08-16')
  await page.getByRole('textbox', { name: '请选择日期' }).press('Enter')
  await expect(page.getByText('1,200').first()).toBeVisible()
  const trendCanvas = page.locator('.section-band canvas').first()
  const trendBox = await trendCanvas.boundingBox()
  expect(trendBox).not.toBeNull()
  await page.mouse.move(trendBox!.x + trendBox!.width / 2, trendBox!.y + trendBox!.height / 2)
  const tooltip = page.locator('.trend-tooltip')
  await expect(tooltip).toBeVisible()
  const tooltipText = await tooltip.innerText()
  const metricOrder = ['播放', '点赞', '评论', '分享', '关注', '转发', '收藏']
  metricOrder.slice(1).forEach((label, index) => expect(tooltipText.indexOf(label)).toBeGreaterThan(tooltipText.indexOf(metricOrder[index])))
  expect(tooltipText).toMatch(/[↑↓→]/)

  const sider = page.locator('.desktop-sider')
  const toggle = page.getByTitle('收起侧边栏')
  const [siderBox, toggleBox] = await Promise.all([sider.boundingBox(), toggle.boundingBox()])
  expect(siderBox).not.toBeNull()
  expect(toggleBox).not.toBeNull()
  expect(Math.abs(toggleBox!.x + toggleBox!.width / 2 - (siderBox!.x + siderBox!.width))).toBeLessThan(3)
  expect(Math.abs(toggleBox!.y + toggleBox!.height / 2 - (siderBox!.y + siderBox!.height / 2))).toBeLessThan(3)
  expect(toggleBox!.width).toBeLessThanOrEqual(22)
  await toggle.click()
  await expect(page.getByTitle('展开侧边栏')).toBeVisible()
  await expect.poll(async () => (await sider.boundingBox())!.width).toBeLessThanOrEqual(72)
  await page.getByTitle('展开侧边栏').click()

  const historyRows = [{ id: 41, start_date: '2026-08-15', end_date: '2026-08-16', created_at: '2026-08-18T00:00:00Z' }]
  await page.route('**/api/ai/provider', (route) => route.fulfill({ json: { id: 1, name: '测试 AI', base_url: 'https://example.test/v1', model: 'test-model', protocol: 'chat_completions', timeout_seconds: 30, api_key_configured: true } }))
  await page.route('**/api/ai/reports?*', (route) => route.fulfill({ json: historyRows }))
  await page.route('**/api/ai/reports/41/analyze', (route) => route.fulfill({ json: {
    ...historyRows[0], report_text: '# 查看结果\n\n- 分析内容',
    snapshot: { account_id: 1, start_date: '2026-08-15', end_date: '2026-08-16', days_with_data: 2, trend: [], totals: {}, averages: {}, previous_start_date: '2026-08-13', previous_end_date: '2026-08-14', previous_trend: [], previous_totals: {} },
  } }))
  await page.route('**/api/ai/reports/41', (route) => route.request().method() === 'DELETE' ? route.fulfill({ status: 204 }) : route.fulfill({ json: historyRows[0] }))
  await page.getByText('AI 建议', { exact: true }).first().click()
  await expect(page.getByRole('button', { name: '查看分析' })).toBeVisible()
  await expect(page.getByRole('button', { name: '编辑' })).toHaveCount(0)
  await page.getByRole('button', { name: '查看分析' }).click()
  await expect(page.getByRole('heading', { name: '查看结果' })).toBeVisible()
  await page.getByRole('button', { name: '删除' }).click()
  await page.locator('.ant-popconfirm-buttons .ant-btn-primary').click()
  await expect(page.getByRole('button', { name: '查看分析' })).toHaveCount(0)

  await page.getByText('数据概览', { exact: true }).first().click()
  await page.getByRole('textbox', { name: '请选择日期' }).fill('2026-08-16')
  await page.getByRole('textbox', { name: '请选择日期' }).press('Enter')
  await page.getByRole('textbox', { name: '请选择日期' }).press('Escape')
  await expect(page.getByText('1,200').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true })

  await page.setViewportSize({ width: 390, height: 844 })
  await page.reload()
  await expect(page.locator('.mobile-nav')).toBeVisible()
  await page.getByRole('textbox', { name: '请选择日期' }).click()
  await page.locator('.ant-picker-dropdown').getByText('16', { exact: true }).click()
  await expect(page.getByText('1,200').first()).toBeVisible()
  await expect(page.locator('.ant-picker-dropdown')).not.toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)

})
